const channels = {
  folder: {
    select: 'folder:select',
  },
  file: {
    read: 'file:read',
    readImage: 'file:read-image',
    remove: 'file:remove',
    saveImage: 'file:save-image',
    showInFolder: 'show-in-folder',
  },
  workspace: {
    backup: 'workspace:backup',
    backupStatus: 'workspace:backup-status',
    restoreBackup: 'workspace:restore-backup',
    getWorkspaceTree: 'workspace:get-tree',
    getTrashItems: 'workspace:get-trash-items',
    treeChanged: 'workspace:tree-changed',
    getCurrentPath: 'workspace:get-current-path',
    initCurrent: 'workspace:init-current',
    selectPath: 'workspace:select-path',
    resetPath: 'workspace:reset-path',
    updateRoot: 'workspace:update-root',
    createWorkspace: 'workspace:create',
    renameWorkspace: 'workspace:rename',
    removeWorkspace: 'workspace:remove',
    purgeWorkspace: 'workspace:purge',
    restoreWorkspace: 'workspace:restore',
    getWorkspaceInfo: 'workspace:get-info',
    updateWorkspaceInfo: 'workspace:update-info',
  },
  document: {
    recoverDocument: 'document:recover',
    createDocument: 'document:create',
    getDocument: 'document:get',
    removeDocument: 'document:remove',
    purgeDocument: 'document:purge',
    restoreDocument: 'document:restore',
    updateDocument: 'document:update',
  },
  setting: {
    getInfo: 'setting:get-info',
    updateAiSettings: 'setting:update-ai-settings',
    saveOpenRouterKey: 'setting:save-openrouter-key',
    deleteOpenRouterKey: 'setting:delete-openrouter-key',
    checkOpenRouter: 'setting:check-openrouter',
    listOpenRouterModels: 'setting:list-openrouter-models',
    updateSelectedEmbeddingModel: 'setting:update-selected-embedding-model',
    updateSelectedLLMModel: 'setting:update-selected-llm-model',
  },
  storyMemory: {
    generate: 'story-memory:generate',
    save: 'story-memory:save',
    getLatest: 'story-memory:get-latest',
  },
  ollama: {
    isRunning: 'ollama:is-running',
    listModels: 'ollama:list-models',
  },
  comment: {
    addExample: 'comment:add-example',
    generateComments: 'comment:generateComments',
    listExamples: 'comment:list-examples',
    removeExample: 'comment:remove-example',
    listGenerated: 'comment:list-generated',
    removeGenerated: 'comment:remove-generated',
  },
};

export = channels;
